#
# 2 Slaves : linux & performance => Label Matric
# xxxx Activities : run-db-unit-tests, run-db-integration-tests, run-upgrade-tests & run-perf-tests


RUN_ACTIVITY:
  - run-db-unit-tests-mysql56
  - run-db-unit-tests-mssql2012
  - run-db-unit-tests-mssql2014
  - run-db-unit-tests-oracle11g
  - run-db-unit-tests-oracle12c
  - run-db-unit-tests-postgresql93

exclude:
  - RUN_ACTIVITY: run-db-unit-tests-mysql56
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-unit-tests-mssql2012
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-unit-tests-mssql2014
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-unit-tests-oracle11g
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-unit-tests-oracle12c
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-unit-tests-postgresql93
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-perf-tests
    SLAVE_TYPE: linux
