#
# 2 Slaves : linux & performance => Label Matric
# xxxx Activities : run-db-unit-tests, run-db-integration-tests, run-upgrade-tests & run-perf-tests


RUN_ACTIVITY:
  - run-db-unit-tests-mysql56
  - run-perf-tests

exclude:
  - RUN_ACTIVITY: run-db-unit-tests-mysql56
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-perf-tests
    SLAVE_TYPE: linux
