#
# 2 Slaves : linux & performance => Label Matric
# xxxx Activities : run-db-unit-tests, run-db-integration-tests, run-upgrade-tests & run-perf-tests


RUN_ACTIVITY:
  - run-db-unit-tests-mysql56
  - run-db-integration-tests-mysql56-cat1
  - run-db-integration-tests-mysql56-cat2
  - run-db-integration-tests-mysql56-cat3
  - run-db-integration-tests-mysql56-cat4
  - run-upgrade-tests-mysql56
  - run-db-unit-tests-postgresql93
  - run-db-integration-tests-postgresql93
  - run-upgrade-tests-postgresql93
  - run-perf-tests

exclude:
  - RUN_ACTIVITY: run-db-unit-tests-mysql56
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-integration-tests-mysql56-cat1
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-integration-tests-mysql56-cat2
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-integration-tests-mysql56-cat3
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-integration-tests-mysql56-cat4
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-upgrade-tests-mysql56
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-unit-tests-postgresql93
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-integration-tests-postgresql93
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-upgrade-tests-postgresql93
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-perf-tests
    SLAVE_TYPE: linux
